<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book [
    <!ELEMENT book (name, pages, author, price)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT pages (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ATTLIST book id CDATA #REQUIRED>
]>
<book id="1">
    <name>Web Technologies</name>
    <pages>156</pages>
    <author>Ram</author>
    <price>Rs. 600</price>
</book>